---
- hosts: all
  remote_user: root
  
  tasks:
    - name: Update the system
      become: true
      yum:
        name: "*"
        state: latest

    - name: Install Docker Amazon Linux 2
      become: true
      shell: amazon-linux-extras install docker

    - name: Make sure docker service is running
      become: true
      systemd:
        name: docker
        state: started
        enabled: yes

    - name: Add the ec2-user to the Docker group
      become: true
      user:
        name: ec2-user
        groups: docker
        append: yes
